### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by marjash** [marjash/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by OksanaMariiash** [comment]
PERSONAL LIFE
1971
Elon Reeve Musk was born in Pretoria, Transvaal, South Africa
1983
Created and wrote a video game called Blastar; sold it for the equivalent of $500
2000
Married college girlfriend Justine Wilson
2002
First son wass born. He died of sudden infant death syndrome (SIDS) at the age of 10 weeks
2004
Twin sons were born
2006
Triplet sons were born
2008
Divorced wife
2010
Married with Talulah Riley
2012
Divorced Riley
2013 
Musk and Riley remarried
2016
Divorced Riley again
2020
The 6th son was born, named X Æ A-12

Education
1990 
Entered Queen's University in Kingston, Ontario.
1995
Was accepted to a Ph.D. program in energy physics/materials science at Stanford University in California
1997
Graduated with a Bachelor of Science (BS) degree in economics from the Wharton School and a Bachelor of Arts (BA) degree in physics

Business career
1995
Musk, his brother Kimbal, and Greg Kouri founded web software company Zip2 with money raised from a small group of angel investors
1999
Co-founded X.com, an online financial services and e-mail payment company, with $10 million from the sale of Zip2
2000
Invested more money into  PayPal
2002
PayPal was acquired by eBay for $1.5 billion in stock, of which Musk received $165 million
2002
Founded SpaceX
2004
Invested in Tesla Motors
2006
SpaceX won $1.6 billion contract to bring cargo to the International Space Station
Provided the initial concept and financial capital for SolarCity, which was then co-founded in 2006 by his cousins Lyndon and Peter Rive.
2007
Became Tesla’s CEO
2010
Tesla IPO
Donated a 25-kW Solar power system
2011
Donated US$250,000 towards a solar power project in Sōma, Japan, a city that had been recently devastated by a tsunami.
2012
SpaceX became the first commercial vehicle to deliver a load of supplies to the International Space Station.
2012
Tesla began deliveries of the all-electric Model S
2013
SolarCity became the second largest solar power provider
Released sketch and concept of the Hyperloop
2015
Announced Hyperloop design competition 
2016
Co-founded Neuralink, a neurotechnology startup company to integrate the human brain with artificial intelligence
Revealed Mars colonization exploration architecture details
2017
Hyperloop One announced first successful test run
2018
Launched his largest rocket Falcon Heavy
2020
First Hyperloop trains started running
