### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by marjash** [marjash/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by OksanaMariiash** [comment]
Likes
Twitter, meme, become a twitter meme, give strange names to children
Mars, anime, trains, C++, rocket

Wants
Colonize Mars and leave this sinful Earth

In popular culture
Musk had a cameo in film Iron Man 2, The Simpsons, The Big Bang Theory, spin-off prequel series Young Sheldon.
In several episodes of South Park, Star Trek universe on the CBS, Rick and Morty.
